import { useEffect, useMemo, useState } from 'react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ChevronLeft, ChevronRight, Maximize2, Minimize2, Presentation } from 'lucide-react';
import { Button } from '../ui/button';
import { Input } from '../ui/input';
import { supabase } from '../../lib/supabase';

type Platform={id:string;name:string;responsible_name:string;display_order:number};
type Metric={id:string;platform_id:string;name:string;unit:string;target_value:number|null};
type Measurement={indicator_id:string;reference_date:string;value:number};
type Report={id:string;platform_id:string;reference_date:string;title:string;status:string};
type Block={id:string;report_id:string;block_type:string;title:string|null;content:any;x:number;y:number;width:number;height:number;z_index:number};

const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'America/Sao_Paulo'});
function format(v:number|undefined,unit:string){if(v===undefined)return '—';if(unit==='%')return `${Number(v).toLocaleString('pt-BR')}%`;if(unit==='R$')return Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});return Number(v).toLocaleString('pt-BR');}

export function IndicatorsPresentation(){
  const [date,setDate]=useState(today());const [platforms,setPlatforms]=useState<Platform[]>([]);const [metrics,setMetrics]=useState<Metric[]>([]);const [measurements,setMeasurements]=useState<Measurement[]>([]);const [reports,setReports]=useState<Report[]>([]);const [blocks,setBlocks]=useState<Block[]>([]);const [index,setIndex]=useState(0);const [fullscreen,setFullscreen]=useState(false);
  useEffect(()=>{void load()},[date]);
  useEffect(()=>{const handler=(e:KeyboardEvent)=>{if(e.key==='ArrowRight')setIndex(i=>Math.min(Math.max(0,reports.length-1),i+1));if(e.key==='ArrowLeft')setIndex(i=>Math.max(0,i-1));if(e.key==='Escape')setFullscreen(false)};window.addEventListener('keydown',handler);return()=>window.removeEventListener('keydown',handler)},[reports.length]);
  async function load(){const [{data:p},{data:m},{data:v},{data:r}]=await Promise.all([
    supabase.from('platforms').select('id,name,responsible_name,display_order').eq('active',true).order('display_order'),
    supabase.from('indicator_definitions').select('id,platform_id,name,unit,target_value').eq('active',true),
    supabase.from('indicator_measurements').select('indicator_id,reference_date,value').lte('reference_date',date).order('reference_date'),
    supabase.from('indicator_reports').select('id,platform_id,reference_date,title,status').eq('report_type','daily').eq('reference_date',date).in('status',['ready','presented']),
  ]);const ps=(p||[]) as Platform[];const rs=((r||[]) as Report[]).sort((a,b)=>(ps.find(x=>x.id===a.platform_id)?.display_order||0)-(ps.find(x=>x.id===b.platform_id)?.display_order||0));setPlatforms(ps);setMetrics((m||[]) as Metric[]);setMeasurements((v||[]) as Measurement[]);setReports(rs);setIndex(i=>Math.min(i,Math.max(0,rs.length-1)));if(rs.length){const {data:b}=await supabase.from('indicator_report_blocks').select('*').in('report_id',rs.map(x=>x.id)).order('z_index');setBlocks((b||[]) as Block[])}else setBlocks([]);}
  const report=reports[index];const platform=platforms.find(p=>p.id===report?.platform_id);const reportBlocks=useMemo(()=>blocks.filter(b=>b.report_id===report?.id),[blocks,report]);
  const current=(id:string)=>measurements.find(m=>m.indicator_id===id&&m.reference_date===date);const previous=(id:string)=>[...measurements.filter(m=>m.indicator_id===id&&m.reference_date<date)].sort((a,b)=>b.reference_date.localeCompare(a.reference_date))[0];const series=(id:string)=>measurements.filter(m=>m.indicator_id===id&&m.reference_date<=date).sort((a,b)=>a.reference_date.localeCompare(b.reference_date)).slice(-12).map(m=>({date:m.reference_date.slice(5),value:Number(m.value)}));
  function renderBlock(block:Block){if(block.block_type==='image')return <img src={block.content?.image_url} className="h-full w-full rounded-xl object-contain"/>;if(block.block_type==='text')return <div className="h-full rounded-xl bg-white/[.04] p-4"><h3 className="font-black">{block.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-white/65">{block.content?.text}</p></div>;const metric=metrics.find(m=>m.id===block.content?.indicator_id);if(!metric)return null;const c=current(metric.id);const p=previous(metric.id);const delta=c&&p?Number(c.value)-Number(p.value):null;if(block.block_type==='kpi')return <div className="flex h-full flex-col justify-between rounded-xl bg-gradient-to-br from-emerald-400/12 to-cyan-400/5 p-4"><div><p className="text-xs uppercase tracking-[.15em] text-white/45">{metric.name}</p><p className="mt-2 text-4xl font-black">{format(c?.value,metric.unit)}</p></div><div className="flex items-end justify-between"><span className={`text-sm font-bold ${delta===null?'text-white/35':delta>=0?'text-emerald-300':'text-rose-300'}`}>{delta===null?'Sem comparação':`${delta>=0?'+':''}${delta.toLocaleString('pt-BR')} vs. anterior`}</span>{metric.target_value!==null&&<span className="text-xs text-white/40">Meta {format(metric.target_value,metric.unit)}</span>}</div></div>;return <div className="h-full rounded-xl bg-white/[.025] p-3"><p className="mb-2 text-sm font-black">{metric.name}</p><div className="h-[calc(100%-28px)]"><ResponsiveContainer width="100%" height="100%"><AreaChart data={series(metric.id)}><defs><linearGradient id={`pres-${metric.id}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#5eead4" stopOpacity={.45}/><stop offset="100%" stopColor="#059669" stopOpacity={.03}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" opacity={.08}/><XAxis dataKey="date" tick={{fill:'#8ba0b5',fontSize:9}} axisLine={false}/><YAxis tick={{fill:'#8ba0b5',fontSize:9}} axisLine={false}/><Tooltip contentStyle={{background:'#06111b',border:'1px solid rgba(255,255,255,.12)',borderRadius:12}}/><Area type="monotone" dataKey="value" stroke="#5eead4" strokeWidth={3} fill={`url(#pres-${metric.id})`}/></AreaChart></ResponsiveContainer></div></div>}
  return <div className={fullscreen?'fixed inset-0 z-[100] bg-[#02070d] p-5 text-white':'space-y-5 text-white'}><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-emerald-300/70">Apresentação diária</p><h1 className="mt-1 text-3xl font-black">{platform?.name||'Nenhuma apresentação pronta'}</h1>{platform&&<p className="mt-1 text-sm text-white/45">{platform.responsible_name} • {index+1} de {reports.length}</p>}</div><div className="flex flex-wrap items-center gap-2"><Input type="date" value={date} onChange={e=>setDate(e.target.value)} className="w-auto border-white/10 bg-black/30"/><Button variant="outline" disabled={index===0} onClick={()=>setIndex(i=>Math.max(0,i-1))} className="border-white/10 bg-white/5 text-white"><ChevronLeft className="h-4 w-4"/></Button><Button variant="outline" disabled={index>=reports.length-1} onClick={()=>setIndex(i=>Math.min(reports.length-1,i+1))} className="border-white/10 bg-white/5 text-white"><ChevronRight className="h-4 w-4"/></Button><Button onClick={()=>setFullscreen(v=>!v)} className="bg-emerald-400 text-black hover:bg-emerald-300">{fullscreen?<Minimize2 className="mr-2 h-4 w-4"/>:<Maximize2 className="mr-2 h-4 w-4"/>}{fullscreen?'Sair':'Tela cheia'}</Button></div></div>{!report?<div className="flex min-h-[65vh] items-center justify-center rounded-[26px] border border-dashed border-white/15 bg-black/25 text-center text-white/35"><div><Presentation className="mx-auto mb-3 h-8 w-8"/><p>Nenhuma plataforma finalizou a apresentação nesta data.</p></div></div>:<div className={`${fullscreen?'h-[calc(100vh-105px)]':'aspect-video'} relative w-full overflow-hidden rounded-[28px] border border-white/10 bg-[radial-gradient(circle_at_20%_20%,rgba(16,185,129,.12),transparent_26%),linear-gradient(145deg,#06111b,#02070d)] shadow-2xl`}><div className="pointer-events-none absolute inset-0 opacity-20" style={{backgroundImage:'linear-gradient(rgba(255,255,255,.08) 1px,transparent 1px),linear-gradient(90deg,rgba(255,255,255,.08) 1px,transparent 1px)',backgroundSize:'32px 32px'}}/>{reportBlocks.length===0?<div className="absolute inset-0 flex items-center justify-center text-white/30">A apresentação está pronta, mas ainda não possui blocos no canvas.</div>:reportBlocks.map(block=><div key={block.id} style={{left:`${block.x}%`,top:`${block.y}%`,width:`${block.width}%`,height:`${block.height}%`,zIndex:block.z_index}} className="absolute overflow-hidden rounded-2xl border border-white/10 bg-black/35 p-1 shadow-[0_18px_50px_rgba(0,0,0,.35)] backdrop-blur-xl">{renderBlock(block)}</div>)}</div>}</div>;
}
