import { useEffect, useMemo, useState } from 'react';
import { useNavigate } from 'react-router';
import { Activity, ArrowRight, BarChart3, CalendarDays, FileBarChart, Presentation, Settings2, Sparkles } from 'lucide-react';
import { Card } from '../ui/card';
import { Button } from '../ui/button';
import { supabase } from '../../lib/supabase';

type Platform={id:string;name:string;responsible_name:string;responsible_id:string;display_order:number;upload_deadline:string};
type Metric={id:string;platform_id:string;name:string;unit:string;target_value:number|null;direction:string};
type Measurement={indicator_id:string;reference_date:string;value:number};
type Submission={platform_id:string;reference_date:string;is_late:boolean;status:string};

function value(v:number,unit:string){if(unit==='%')return `${Number(v).toLocaleString('pt-BR')}%`;if(unit==='R$')return Number(v).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});return Number(v).toLocaleString('pt-BR');}

export function IndicatorsHub(){
  const navigate=useNavigate();const [platforms,setPlatforms]=useState<Platform[]>([]);const [metrics,setMetrics]=useState<Metric[]>([]);const [measurements,setMeasurements]=useState<Measurement[]>([]);const [submissions,setSubmissions]=useState<Submission[]>([]);const [loading,setLoading]=useState(true);
  const today=new Date().toLocaleDateString('sv-SE',{timeZone:'America/Sao_Paulo'});
  useEffect(()=>{void load()},[]);
  async function load(){setLoading(true);const [{data:p},{data:m},{data:v},{data:s}]=await Promise.all([
    supabase.from('platforms').select('id,name,responsible_name,responsible_id,display_order,upload_deadline').eq('active',true).order('display_order'),
    supabase.from('indicator_definitions').select('id,platform_id,name,unit,target_value,direction').eq('active',true).order('display_order'),
    supabase.from('indicator_measurements').select('indicator_id,reference_date,value').order('reference_date',{ascending:false}).limit(1500),
    supabase.from('indicator_submissions').select('platform_id,reference_date,is_late,status').eq('reference_date',today),
  ]);setPlatforms((p||[]) as Platform[]);setMetrics((m||[]) as Metric[]);setMeasurements((v||[]) as Measurement[]);setSubmissions((s||[]) as Submission[]);setLoading(false);}
  const stats=useMemo(()=>({platforms:platforms.length,metrics:metrics.length,sent:new Set(submissions.filter(s=>['uploaded','extracting','extracted','confirmed'].includes(s.status)).map(s=>s.platform_id)).size,late:submissions.filter(s=>s.is_late).length}),[platforms,metrics,submissions]);

  return <div className="space-y-6 text-white">
    <section className="overflow-hidden rounded-[28px] border border-white/10 bg-black/35 p-6 shadow-2xl backdrop-blur-xl lg:p-8"><div className="flex flex-col gap-6 lg:flex-row lg:items-end lg:justify-between"><div><div className="mb-3 flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.24em] text-emerald-300/80"><Sparkles className="h-4 w-4"/>FLOW Intelligence</div><h1 className="max-w-4xl text-3xl font-black tracking-tight sm:text-4xl lg:text-5xl">Central de Indicadores</h1><p className="mt-3 max-w-3xl text-sm leading-6 text-white/60 sm:text-base">Cada plataforma reúne várias métricas. Os prints viram dados históricos, comparações, gráficos e apresentações.</p></div><div className="flex flex-wrap gap-2"><Button onClick={()=>navigate('/indicadores/studio')} className="bg-emerald-400 text-black hover:bg-emerald-300"><Presentation className="mr-2 h-4 w-4"/>Preparar apresentação</Button><Button variant="outline" onClick={()=>navigate('/indicadores/analises')} className="border-white/15 bg-white/5 text-white"><FileBarChart className="mr-2 h-4 w-4"/>Análises e relatórios</Button><Button variant="outline" onClick={()=>navigate('/indicadores/configuracao')} className="border-white/15 bg-white/5 text-white"><Settings2 className="mr-2 h-4 w-4"/>Configurar plataformas</Button></div></div></section>
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{[['Plataformas',stats.platforms,BarChart3],['Métricas monitoradas',stats.metrics,Activity],['Plataformas enviadas hoje',stats.sent,CalendarDays],['Envios atrasados hoje',stats.late,CalendarDays]].map(([label,n,Icon]:any)=><Card key={label} className="border-white/10 bg-black/30 p-5 text-white"><div className="flex items-center justify-between"><div><p className="text-xs uppercase tracking-[.16em] text-white/40">{label}</p><p className="mt-2 text-3xl font-black">{loading?'—':n}</p></div><div className="rounded-2xl border border-emerald-400/20 bg-emerald-400/10 p-3"><Icon className="h-5 w-5 text-emerald-300"/></div></div></Card>)}</section>
    <section className="grid gap-4 xl:grid-cols-2">{platforms.map(platform=>{const defs=metrics.filter(m=>m.platform_id===platform.id);const submission=submissions.find(s=>s.platform_id===platform.id);return <Card key={platform.id} className="overflow-hidden border-white/10 bg-black/30 text-white"><div className="border-b border-white/10 p-5"><div className="flex items-start justify-between gap-4"><div><div className="flex items-center gap-2"><span className="rounded-full bg-emerald-400/10 px-2 py-1 text-[10px] font-black text-emerald-300">#{platform.display_order}</span><h2 className="text-xl font-black">{platform.name}</h2></div><p className="mt-2 text-sm text-white/45">{platform.responsible_name} • enviar até {String(platform.upload_deadline).slice(0,5)}</p><p className={`mt-2 text-xs font-bold ${submission?.is_late?'text-rose-300':submission?'text-emerald-300':'text-white/35'}`}>{submission?.is_late?'Enviado com atraso':submission?'Enviado hoje':'Pendente hoje'}</p></div><Button variant="outline" onClick={()=>navigate(`/indicadores/studio?platform=${platform.id}`)} className="border-white/15 bg-white/5 text-white">Abrir <ArrowRight className="ml-2 h-4 w-4"/></Button></div></div><div className="grid gap-3 p-5 sm:grid-cols-2">{defs.length===0?<p className="col-span-full text-sm text-white/40">Nenhuma métrica configurada para esta plataforma.</p>:defs.slice(0,8).map(metric=>{const history=measurements.filter(v=>v.indicator_id===metric.id).sort((a,b)=>b.reference_date.localeCompare(a.reference_date));const current=history[0];const previous=history[1];const delta=current&&previous?Number(current.value)-Number(previous.value):null;const good=delta===null?null:metric.direction==='lower'?delta<0:delta>0;return <div key={metric.id} className="rounded-2xl border border-white/10 bg-white/[.03] p-4"><p className="text-xs text-white/45">{metric.name}</p><div className="mt-2 flex items-end justify-between gap-2"><p className="text-2xl font-black">{current?value(Number(current.value),metric.unit):'—'}</p>{delta!==null&&<span className={`text-xs font-bold ${good?'text-emerald-300':'text-rose-300'}`}>{delta>=0?'+':''}{delta.toLocaleString('pt-BR')}</span>}</div></div>})}</div></Card>})}</section>
  </div>;
}
